name: daily_coding_challenges
description: A new Flutter application.

version: 1.0.6+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+1
  firebase_messaging: ^5.0.2
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.3
  animated_text_kit: ^2.0.0
  shared_preferences: ^0.5.1+2
  modal_progress_hud: ^0.1.3
  url_launcher: any
  share: ^0.6.3+5
  firebase_admob: ^0.9.0+10
  connectivity: ^0.3.0
  webview_flutter: ^0.3.19+9
  flutter_email_sender: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/google_logo.png
   - assets/cloud.png
   - assets/infy tech logo.png
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Open Sans SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
